config/routes.rb
Rails.application.routes.draw do
  root "org_profiles#home"
  
  get "/orgs", to: "org_profiles#index"

  get "/orgs/:id", to: "org_profiles#public_show"
  
  get "/profiles/:id", to: "user_profiles#show"

  get "/profiles/:id/edit", to: "user_profiles#edit"

  get "/orgs/:id/new_opportunity", to: "tasks#new"

  get "/orgs/:org_profile_id/tasks/:task_id", to: "tasks#show"

  get "/profiles/:user_id/orgs/:org_profile_id/tasks/:task_id", to: "tasks#show"

  get "/orgs/:id/profile", to: "org_profiles#admin_show"
  
  get "/orgs/:id/update", to: "org_profiles#update"

  #get "/org_profiles/:id", to: "org_profiles#update"

  get "/profiles/:user_id/log_task/:task_id", to: "user_profiles#log_task"

  get "/create_account", to: "user_profiles#new"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :org_profiles do
    resources :tasks
  end

  resources :user_profiles do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/org_profile.rb
class OrgProfile < ApplicationRecord
    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :org_profile

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
    belongs_to :user,
      class_name: "UserProfile",
      optional: true

      # DO NOT SUBMIT this doesn't need to be a UserProfile if we're just using the ID to get the full user right?
      # also maybe rename to friend_ids
    has_many :friends,
      class_name: "UserProfile"

    has_many :tasks

    validates :email, presence: true, format: { with: /.*@.*/, message: "this doesn't seem like a valid email" }
    validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/org_profiles_controller.rb
class OrgProfilesController < ApplicationController  
  #http_basic_authenticate_with name: "org_user", password: "strong_password", only: [:admin_show]  
  def home
   end
  
    def index
      @org_profiles = OrgProfile.all
    end

    def show
        @org_profile = OrgProfile.find(params[:id])
    end
  
    def new
    end

    def create
    end

    def edit
    end

    def update
      @org_profile = OrgProfile.find(params[:id])

      if @org_profile.update(org_profile_params)
        #redirect_to @org_profile
        puts "THIS HAPPENED"
      else
        render :bad, status: :unprocessable_entity
      end
    end

    def public_show
      show
    end

    def admin_show
      show
    end

    private
    def org_profile_params
      params.permit(:name, :contact_info, :mission_statement, :blurb, :tasks)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
      @tasks = Task.all
    end
  
    def show
      unless params[:task_id].nil?
        @task_id = params[:task_id]
        puts "task ID is ", :task_id
      else 
        @task_id = params[:id]
      end
      @task = Task.find(@task_id)
      @org_profile = OrgProfile.find(params[:org_profile_id])
      @user_signed_in = false
      if defined? params[:user_id]
        @user_signed_in = true
        @user_id = params[:user_id]
      end
    end

    def new
        @task = Task.new
    end

    def create
        @org_profile = OrgProfile.find(params[:org_profile_id])
        @task = @org_profile.tasks.create(task_params)
        redirect_to org_profile_path(@org_profile)
    end

    def edit
      @task = Task.find(params[:id])
    end

    def update
        @task = Task.find(params[:id])

        if @task.save
          redirect to @task
        else
          render :new, status: :unprocessable_entity
        end
    end

    private
      def task_params
        params.require(:task).permit(:title, :blurb)
      end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  #http_basic_authenticate_with name: "user", password: "mid_password", only: [:admin_show]
  def index
    @user_profiles = UserProfile.all
  end
  
  def new
    puts "in new ~~~~~~~~~~~~~~~~`"
    @user_profile = UserProfile.new
  end

  def create
    puts "in create !!!!!!!!!!!!"
    @user_profile = UserProfile.new(user_profile_params)
    puts "profile params are ", user_profile_params
    if @user_profile.save
      puts "this seems like the GOOD one"
      redirect_to @user_profile
    else
      puts "this seems like the BAD one : ("
      puts @user_profile.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def log_task
    @user_profile = UserProfile.find(params[:user_id])
    @task = Tasks.find(params[:task_id])

    if @user_profile.update(user_profile_params)
      # TODO redirect to something that says "add more" and "go to dashboard"
      redirect_to @user_profile
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @user_profile = UserProfile.find(params[:id])
    @friends = []

 #   puts "****************************"
    # @user_profile.friends_id.each do |friend_id|
    #   @friends.push(UserProfile.find(@user_profile.friend_id))
    #   puts "friend added"
    # end
  end

  def edit
    @user_profile = UserProfile.find(params[:id])
  end

  def update
    @user_profile = UserProfile.find(params[:id])

    if @user_profile.update(user_profile_params)
      # puts "000000000******************************"
      redirect_to @user_profile
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def user_profile_params
      params.require(:user_profile).permit(:password, :name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/org_profiles_helper.rb
module OrgProfilesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VolunteeringTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/org_profiles/_show.html.erb
<h1><%= org_profile.name %></h1>

<h2>who we are</h2>
<%= org_profile.mission_statement %>

<h2>what we stand for</h2>
<%= org_profile.blurb %>

<h2>how to get involved</h2>
<ul>
<% org_profile.tasks.each do |task| %>
<li><%= link_to task.title, org_profile_task_path(org_profile, task) %>
<a href="/orgs/<%= org_profile.id %>/tasks/<%= task.id %>">task.title</a>
<%= task.blurb %></li>
<% end %>
</ul>

<style>
body {
  font-family: 'Courier New', monospace;
  background-color:#A0BFB6
}
</style>

app/views/org_profiles/admin_show.html.erb
<%= render "show", org_profile: @org_profile %>

<%= link_to "edit organization details", "update" %>

<h3>Add opportunity:</h3>
<%= form_with model: [ @org_profile, @org_profile.tasks.build ] do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :blurb %><br>
    <%= form.text_area :blurb %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/org_profiles/bad.html.erb
<h1>this did not work i am sorry</h1>

app/views/org_profiles/home.html.erb
<h1>Volunteering Tracker</h1>
<ul>
  <li>gameify your altruism!</li>
  <li>compete with friends!</li>
  <li>find new opportunities to make the world a better place!</li>
</ul>

<a href="/orgs">browse organizations</a>
|
<a href="/create_account">make an account</a>

<style>
body {
  font-family: 'Courier New', monospace;
  background-color:#A0BFB6
}
</style>

app/views/org_profiles/index.html.erb
<h1>This is where orgs go</h1>

<ul>
  <% @org_profiles.each do |org_profile| %>
    <h3>
      <a href="/orgs/<%= org_profile.id %>">
        <%= org_profile.name %>
      </a>
      <h5>contact us at: <%= org_profile.contact_info %></h5>
    </h3>
  <% end %>
</ul>

<style>
body {
  font-family: 'Courier New', monospace;
  background-color:#A0BFB6
}
</style>

app/views/org_profiles/public_show.html.erb
<%= render "show", org_profile: @org_profile %>

app/views/org_profiles/update.html.erb
<h2>who we are</h2>
<%= form_with model: @org_profile do |form|%>
  <% form.label :mission_statement %><br>
  <%= form.text_field :mission_statement %><br>
  <%= form.submit "update"%>
<% end %>

<h2>what we stand for</h2>
<%= form_with model: @org_profile do |form|%>
  <% form.label :blurb %><br>
  <%= form.text_area :blurb %><br>
  <%= form.submit "update"%>
<% end %>

<h3>Add opportunity:</h3>
<%= form_with model: [ @org_profile, @org_profile.tasks.build ] do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :blurb %><br>
    <%= form.text_area :blurb %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<style>
body {
  font-family: 'Courier New', monospace;
  background-color:#A0BFB6
}
</style>

app/views/tasks/_form.html.erb
<%= form_with model: task do |form| %>
    <div>
      <%= form.label :task %><br>
      <%= form.text_field :blurb %>
      <% task.errors.full_messages_for(:task).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :blurb %><br>
      <%= form.text_area :blurb %><br>
      <% task.errors.full_messages_for(:blurb).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/tasks/_show.html.erb
<h1><%= @org_profile.name %></h1>

<h2><%= @task.title %></h2>
<%= @task.blurb %>

<!-- TODO if the user is logged in, pass info to this --!>
<%= if @user_signed_in %>
  <p>
    <a href="tasks/<%= params[:task_id] %>/users/">Log this task</a>
  </p>
<% end %>

<style>
body {
  font-family: 'Courier New', monospace;
  background-color:#A0BFB6
}
</style>

app/views/tasks/new.html.erb
<h1>New Opportunity</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1><%= @org_profile.name %></h1>

<h2><%= @task.title %></h2>
<%= @task.blurb %>

<!-- TODO if the user is logged in, pass info to this --!>
<% if @user_signed_in %>
  <p>
    <a href="/tasks/<%= @task_id %>/users/<%= @user_id %>">Log this task</a>
  </p>
  <% else %>
  <p>
  Sign in to log this task
  </p>
  <% end %>

<style>
body {
  font-family: 'Courier New', monospace;
  background-color:#A0BFB6
}
</style>

app/views/user_profiles/edit.html.erb
<h1><%= @user_profile.name %>'s profile</h1>

<h2>points accumulated</h2>
<%= @user_profile.total_points %>
<h3>recent activities</h3>
<h4>log volunteering</h4>
<%= form_with model: [ @user_profile, @user_profile.tasks.build ] do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <% @user_profile.errors.full_messages_for(:tasks).each do |message| %>
    <%= message %>
    <% end %>
    <%= form.submit "log" %>
  <% end %>

<%= form_with model: @user_profile do |form| %>
  <h3><%= form.label :email %></h3>
  <%= form.text_field :email %>
  <% @user_profile.errors.full_messages_for(:email).each do |message| %>
    <%= message %>
  <% end %>
  <%= form.submit "update email" %>
<% end %> 

<style>
body {
  font-family: 'Courier New', monospace;
  background-color:#A0BFB6
}
</style>

app/views/user_profiles/log_task.html.erb
<h1><%= @org_profile.name %></h1>

<h2><%= @task.title %></h2>
<%= @task.blurb %>

<%= form_with model: [ @user_profile, @user_profile.tasks.build ] do |form| %>
  <%= form.label :hours %>
  <%= form.text_field :hours %>
  <% @user_profile.errors.full_messages_for(:tasks).each do |message| %>
    <%= message %>
    <% end %>
    <%= form.submit "log" %>
  <% end %>

app/views/user_profiles/new.html.erb
<h1>Welcome!</h1>

<%= form_for @user_profile do |form| %>
   <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
    <% @user_profile.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div><br>
 
  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% @user_profile.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label :password %><br>
    <%= form.text_field :password %><br>
    Password must be at least 8 characters.
    <% @user_profile.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.submit "Create account" %>
  </div>
<% end %>

<style>
body {
  font-family: 'Courier New', monospace;
  background-color:#A0BFB6
}
</style>

app/views/user_profiles/show.html.erb
<h1><%= @user_profile.name %>'s profile</h1>

<h2>points accumulated</h2>
<%= @user_profile.total_points %>

<h2>tasks accomplished</h2>
<%= @user_profile.tasks.each do |task| %>
  <%= task.title %>
<% end %>

<style>
body {
  font-family: 'Courier New', monospace;
  background-color:#A0BFB6
}
</style>